/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "paper.h"

bool_t
xdr_PAPER (XDR *xdrs, PAPER *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->iPaperNo))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->szAuthors, MAX_AUTHOR_NAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->szPaperTitle, MAX_PAPER_NAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->szFileName, MAX_FILE_NAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->lFileSize))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->ByteFileChunk, MAX_BUF))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->iChunkIndex))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->lChunkSize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FILEINFO (XDR *xdrs, FILEINFO *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->iPaperIndex))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->iChunkIndex))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->lRemainingSize))
		 return FALSE;
	return TRUE;
}
