/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "paper.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
paper_storage_server_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		PAPER senddetails_1_arg;
		int fetchinfo_1_arg;
		FILEINFO fetchdetails_1_arg;
		int fetchlist_1_arg;
		int removedetails_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SendDetails:
		_xdr_argument = (xdrproc_t) xdr_PAPER;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) senddetails_1_svc;
		break;

	case FetchInfo:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_PAPER;
		local = (char *(*)(char *, struct svc_req *)) fetchinfo_1_svc;
		break;

	case FetchDetails:
		_xdr_argument = (xdrproc_t) xdr_FILEINFO;
		_xdr_result = (xdrproc_t) xdr_PAPER;
		local = (char *(*)(char *, struct svc_req *)) fetchdetails_1_svc;
		break;

	case FetchList:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_PAPER;
		local = (char *(*)(char *, struct svc_req *)) fetchlist_1_svc;
		break;

	case RemoveDetails:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) removedetails_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PAPER_STORAGE_SERVER, VERSION1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PAPER_STORAGE_SERVER, VERSION1, paper_storage_server_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PAPER_STORAGE_SERVER, VERSION1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PAPER_STORAGE_SERVER, VERSION1, paper_storage_server_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PAPER_STORAGE_SERVER, VERSION1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
